spring:
  application:
    name: evently
  datasource:
    driver-class-name: org.h2.Driver
    username: a
    password: a
    url: "jdbc:h2:mem:evently;DB_CLOSE_ON_EXIT=FALSE"
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
bookshelf:
  app:
    jwtSecret: xGVgsxuqBU3xuv9J
    expirationMs: 86400000